language: objective-c
osx_image: xcode8.3
branches:
  only:
    - master
xcode_project: UnitTest.xcodeproj
xcode_scheme: UnitTest
script: xcodebuild clean && xcodebuild test -project UnitTest.xcodeproj -scheme UnitTest -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7 Plus,OS=10.3.1' CODE_SIGNING_REQUIRED=NO